#!/usr/bin/env Rscript
# ==============================================================================
# 21_publication_figures.R
# ==============================================================================
#
# GOAL:
#   Generate high-quality, annotated figures specifically targeted for
#   publication, manuscripts, or thesis chapters.  These figures often combine
#   outputs from multiple upstream analytical scripts into a single, polished
#   composite (e.g., Swimmer Plot + Mutation Map).
#
# WHY THIS SCRIPT EXISTS:
#   Analytical scripts (e.g., 15_, 18_) produce utilitarian tracking plots
#   sufficient for interpretation.  This separate script applies project-wide
#   aesthetics, careful labelling, and final polish without cluttering the
#   core analytical pipeline with ggplot2 aesthetic minutiae.
#
# ------------------------------------------------------------------------------
# Purpose:
#   - Generate high-quality, annotated figures for the manuscript.
#
# Legacy output (only when RUN_LEGACY_PUBLICATION_FIGURES=1):
#   - plots/publication/Fig1_Swimmer_Plot.png
#
# Retired output:
#   - plots/publication/Fig2_Mutation_Map.png
#     This pooled contig-local coordinates across different references and used
#     a hard-coded genome length. Use plots/final/Fig08_reference_aware_variant_map
#     from 35_final_figure_pack.R instead.
#
# Purpose:
#   - Generate high-quality, annotated figures for the manuscript.
# ==============================================================================

source("00_config.R")
source("R/pipeline_qc_helpers.R")
source("R/plot_helpers.R")
suppressPackageStartupMessages({
    library(dplyr)
    library(readr)
    library(ggplot2)
    library(tidyr)
    library(stringr)
    library(gridExtra)
    library(scales)
})

msg("Starting 21_publication_figures.R")

# Ensure output dir
DIR_PUB <- file.path(DIR_PLOTS, "publication")
ensure_dir(DIR_PUB)

legacy_publication_enabled <- tolower(trimws(Sys.getenv(
    "RUN_LEGACY_PUBLICATION_FIGURES", unset = "0"
))) %in% c("1", "true", "yes")

retirement_note <- file.path(DIR_PUB, "README_RETIRED.md")
writeLines(c(
    "# Retired Phase 3 publication figures",
    "",
    "`21_publication_figures.R` is a superseded Phase 3 figure layer and is skipped by default.",
    "Set `RUN_LEGACY_PUBLICATION_FIGURES=1` only to reproduce the legacy swimmer plot for comparison.",
    "",
    "`Fig2_Mutation_Map.png` is retired and is never regenerated by this script. The old map",
    "pooled contig-local positions from different reference assemblies and represented every",
    "genome with a fixed length, so its x coordinates were not scientifically comparable.",
    "Use `plots/final/Fig08_reference_aware_variant_map.{png,pdf}`, generated by",
    "`35_final_figure_pack.R`, which validates each reference/contig/position and derives",
    "cumulative coordinates and genome lengths from the exact reference FASTA. Existing copies",
    "of the old mutation-map PNG are historical artifacts and must not be used.",
    "",
    "The canonical replacement for the legacy swimmer plot is",
    "`plots/final/Fig06_longitudinal_trajectories.{png,pdf}`."
), retirement_note)

historical_mutation_png <- file.path(DIR_PUB, "Fig2_Mutation_Map.png")
if (file.exists(historical_mutation_png)) {
    msg(paste0(
        "WARNING: historical retired artifact remains on disk and must not be used: %s. ",
        "It is not regenerated by this script; use plots/final/Fig08_reference_aware_variant_map instead."
    ), historical_mutation_png)
}

if (!legacy_publication_enabled) {
    msg(paste0(
        "Skipping superseded Phase 3 publication figures. Canonical replacements are generated ",
        "by 35_final_figure_pack.R; retirement note: %s"
    ), retirement_note)
} else {
    msg("Legacy publication opt-in enabled; reproducing Fig1 only. Fig2 remains retired.")

# 1. Figure 1: Swimmer Plot (Enhanced)
# ------------------------------------------------------------------------------
timelines <- read_csv(file.path(DIR_RESULTS, "longitudinal", "participant_timelines.csv"), show_col_types = FALSE)
analysis_keys <- read_csv(FILE_ANALYSIS_CLINICAL_COHORT, show_col_types = FALSE) %>%
    transmute(Participant_id = as.character(.data$Participant_id),
              tp_lab = normalise_timepoint_preserve_events(.data$tp_lab)) %>%
    distinct()
timeline_keys <- timelines %>%
    transmute(Participant_id = as.character(.data$Participant_id),
              tp_lab = normalise_timepoint_preserve_events(.data$tp_lab)) %>%
    distinct()
if (nrow(timeline_keys) != nrow(timelines) ||
    nrow(anti_join(analysis_keys, timeline_keys, by = c("Participant_id", "tp_lab"))) ||
    nrow(anti_join(timeline_keys, analysis_keys, by = c("Participant_id", "tp_lab")))) {
    stop("participant_timelines.csv does not exactly match the selected Longcycler analysis cohort")
}

# Filter for participants with at least 2 timepoints
pids_multi <- timelines %>%
    group_by(Participant_id) %>%
    filter(n() > 1) %>%
    pull(Participant_id) %>%
    unique()

df_swim <- timelines %>%
    filter(Participant_id %in% pids_multi, !is.na(Time_Order)) %>%
    prefer_primary_uti_status() %>%
    mutate(
        Status = UTI_Status,
        Participant_id = factor(Participant_id),
        Status = factor(Status, levels = c("Not_UTI", "UTI")),
        Plot_Label = if ("Plot_TP_Label_Poster" %in% names(.)) Plot_TP_Label_Poster else Timepoint,
        Plot_Label = reorder(factor(Plot_Label), Time_Order)
    )

p1 <- ggplot(df_swim, aes(x = Plot_Label, y = Participant_id)) +
    geom_line(aes(group = Participant_id), color = "gray80") +
    geom_point(aes(color = Status, shape = Status), size = 3) +
    scale_colour_uti_status() +
    scale_shape_manual(values = c("Not_UTI" = 17, "UTI" = 16), name = "Primary UTI status") +
    theme_minimal() +
    labs(
        title = "Longitudinal Primary UTI Status Trajectories",
        subtitle = "Participants with multiple timepoints",
        x = "Timepoint",
        y = "Participant ID"
    ) +
    theme(
        axis.text.y = element_text(size = 6),
        legend.position = "bottom"
    )

# Annotate Switchers
# We can add a red box or label around the switchers
# Or just make them bold in Y axis? Hard in ggplot.
# Let's add a text label.

ggsave(file.path(DIR_PUB, "Fig1_Swimmer_Plot.png"), p1, width = 8, height = 10, bg = "white")
msg("Saved Fig1_Swimmer_Plot.png")

# 2. Figure 2: Mutation Map (retired)
# ------------------------------------------------------------------------------
msg(paste0(
    "Fig2_Mutation_Map.png is retired and was not regenerated; use ",
    "plots/final/Fig08_reference_aware_variant_map.{png,pdf}."
))
}

msg("Done.")
