#!/usr/bin/env bash
# Generated by scripts/audit_rUTIs.R
set -euo pipefail
shopt -s nullglob

# Moves
mkdir -p "docs/slides" && mv -i "Virulence factors.pptx" "docs/slides/"
mkdir -p "results/legacy" && mv -i "vfdb_hits_all_assemblies.csv" "results/legacy/"
mkdir -p "docs/slides" && mv -i "Poster_upec.pptx" "docs/slides/"
mkdir -p "docs/papers" && mv -i "Recurrent E. coli Urinary Tract Infections in Nursing Homes- Insight in Sequence Types and Antibiotic Resistance Patterns.pdf" "docs/papers/"
mkdir -p "docs/papers" && mv -i "Bacterial virulence phenotypes of Escherichia coli and host susceptibility determines risk for urinary tract infections.pdf" "docs/papers/"
mkdir -p "docs/papers" && mv -i "YELLOW RoUTIne.pdf" "docs/papers/"
mkdir -p "docs/papers" && mv -i "Virulence Mechanisms of Common Uropathogens and Their Intracellular Localisation within Urothelial Cells.pdf" "docs/papers/"
mkdir -p "docs/papers" && mv -i "Whole-genome characterisation of Escherichia coli isolates from older women with urinary tract infection or asymptomatic bacteriuria.docx" "docs/papers/"
mkdir -p "docs/papers" && mv -i "e.coli_manuscript_vs7_MB_CS_MvdB.docx" "docs/papers/"
mkdir -p "docs/papers" && mv -i "dkac307.pdf" "docs/papers/"
mkdir -p "docs/papers" && mv -i "results/plots/variable_gene_heatmap.pdf" "docs/papers/"
mkdir -p "results/legacy" && mv -i "vf_hits.rds" "results/legacy/"
mkdir -p "docs/papers" && mv -i "results/plots/overview_within_person_status_all_samples.pdf" "docs/papers/"
mkdir -p "docs/slides" && mv -i "Longread_UTI_interim.pptx" "docs/slides/"
mkdir -p "docs/papers" && mv -i "results/plots/overview_plots.pdf" "docs/papers/"
mkdir -p "docs/slides" && mv -i "YELLOW_RoUTIne_Key_Results_Slide copy.pptx" "docs/slides/"
mkdir -p "docs/papers" && mv -i "Analysis of Enterobacter hormaechei.docx" "docs/papers/"
mkdir -p "docs/papers" && mv -i "results/plots/within_person_status_all_samples_single_panel.pdf" "docs/papers/"
mkdir -p "results/legacy" && mv -i "vfdb_presence_absence_matrix.csv" "results/legacy/"
mkdir -p "docs/papers" && mv -i "results/plots/overview_status_story.pdf" "docs/papers/"
mkdir -p "docs/papers" && mv -i "results/plots/within_person_status_pid_by_tp_subdivided.pdf" "docs/papers/"
mkdir -p "docs/papers" && mv -i "Rplots.pdf" "docs/papers/"
mkdir -p "docs/papers" && mv -i "results/plots/within_person_status_all_individuals_bubbles.pdf" "docs/papers/"
mkdir -p "docs/papers" && mv -i "results/mlst/top20_STs.pdf" "docs/papers/"
mkdir -p "docs/papers" && mv -i "results/ST_vs_replicon_network.pdf" "docs/papers/"
mkdir -p "docs/papers" && mv -i "results/replicon_cooccurrence.pdf" "docs/papers/"
mkdir -p "docs/papers" && mv -i "results/replicon_heatmap.pdf" "docs/papers/"
mkdir -p "results/legacy" && mv -i "vfdb_gain_loss_by_participant.csv" "results/legacy/"
mkdir -p "docs/slides" && mv -i "~$Virulence factors.pptx" "docs/slides/"
mkdir -p "docs/papers" && mv -i "~$ole-genome characterisation of Escherichia coli isolates from older women with urinary tract infection or asymptomatic bacteriuria.docx" "docs/papers/"

# Deletes
rm -f "triangle.ids"
rm -f "triangle.sorted"

echo "Done."
