#!/bin/bash
# ==============================================================================
# RUN_COMPLETE_ANALYSIS.sh
# ------------------------------------------------------------------------------
# Complete pipeline execution script for rUTIs project
# Runs all 4 phases in order
# ==============================================================================

set -e  # Exit on error
set -u  # Exit on undefined variable

echo "=========================================="
echo "rUTIs Complete Analysis Pipeline"
echo "Started: $(date)"
echo "=========================================="

# Check conda environment
if [ -z "${CONDA_DEFAULT_ENV:-}" ]; then
    echo "⚠️  WARNING: No conda environment active. Activate with:"
    echo "   conda activate asm-snp-x86"
    exit 1
fi

echo "✓ Conda environment: $CONDA_DEFAULT_ENV"

# ============================================================================
# Phase 0: Clinical Data Foundation
# ============================================================================
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PHASE 0: Clinical Data Foundation [Est: 2 min]"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo "[1/4] Loading clinical data..."
Rscript 00a_load_clean_clinical.R
echo "[2/4] Classifying episodes..."
Rscript 00b_classify_episodes.R
echo "[3/4] Deriving display-only poster timepoints..."
Rscript 00d_derive_plot_timepoints.R
echo "[4/4] Generating clinical plots..."
Rscript 00c_plot_clinical_summary.R

echo "✓ Phase 0 complete: primary status maps and clinical diagnostics created"

# ============================================================================
# Phase 1: WGS Processing (LONGEST PHASE)
# ============================================================================
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PHASE 1: WGS Processing [Est: 1-2 hours total]"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo "[1/6] Assembly QC [~2 min]..."
Rscript 12a_wgs_qc.R
echo "✓ QC complete"

echo "[2/6] Core SNP calling with Parsnp [~30-60 min - SLOWEST STEP]..."
Rscript 12b_core_snp.R
echo "✓ Core SNPs complete"

echo "[3/6] Pangenome analysis with Panaroo [~15 min]..."
Rscript 12c_panaroo.R
echo "✓ Pangenome complete"

echo "[4/6] Selection visualization [~2 min]..."
Rscript 13_visualise_panaroo_selection.R
echo "✓ Visualization complete"

echo "[5/6] Gene presence/absence matrix [~5 min]..."
Rscript 02_gene_presence_analysis.R
echo "✓ Gene presence matrix created"

echo "[6/6] Active RIVM/provider MLST integration [~3 min]..."
Rscript 06_MLST.R
echo "✓ Active RIVM/provider MLST complete"

echo "✓ Phase 1 complete: WGS data processed"

# ============================================================================
# Phase 1b: Additional Plots & Exploration (OPTIONAL)
# ============================================================================
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PHASE 1b: Additional Plots [Est: 10 min total]"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

if [ "${RUN_LEGACY_EXPLORATORY_PLOTS:-0}" = "1" ]; then
    Rscript 03_plotting.R
    echo "✓ Legacy exploratory plots created"
else
    echo "↪ Skipping 03_plotting.R legacy exploratory plots."
    echo "  Canonical UTI-vs-Not_UTI VF figures are generated by scripts 23-30."
fi

Rscript 04_gene_breakdown.R
echo "✓ Focused gene analysis complete"

Rscript 05_gene_overview_plots.R
echo "✓ Gene distribution plots created"

Rscript 07_explore_MLST.R
echo "✓ MLST exploration plots created"

Rscript 08_core_vs_plasmid.R
echo "✓ Core vs plasmid comparison complete"

Rscript 09_inc_plasmid_network.R
echo "✓ Plasmid network visualization created"

Rscript 10_replicon_heatmap.R
echo "✓ Plasmid replicon heatmap created"

echo "✓ Phase 1b complete: Additional plots generated"

# ============================================================================
# Phase 2: Comparative Genomics
# ============================================================================
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PHASE 2: Comparative Genomics [Est: 15 min]"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo "[1/4] Within-host strain comparison [~5 min]..."
Rscript 11_compare_strains.R --participants ALL
echo "✓ Strain comparison complete"

echo "[2/4] Building canonical VF dataset for UTI vs Not_UTI modelling..."
Rscript 22_vf_build_analysis_dataset.R
echo "✓ VF dataset built"

echo "[3/4] Genotype-phenotype model: UTI vs Not_UTI [~8 min]..."
Rscript 14_genotype_phenotype_model.R
echo "✓ UTI vs Not_UTI model complete"

echo "[4/4] Lineage risk analysis [~2 min]..."
Rscript 17_lineage_analysis.R
echo "✓ Lineage analysis complete"

echo "✓ Phase 2 complete: Comparative analysis done"

# ============================================================================
# Phase 3: Longitudinal & Mechanism
# ============================================================================
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PHASE 3: Longitudinal & Mechanism [Est: 5 min]"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo "[1/6] Reconstructing patient timelines [~1 min]..."
Rscript 15_longitudinal_patterns.R
echo "✓ Timelines reconstructed"

echo "[2/6] Within-host evolution analysis [~1 min]..."
Rscript 16_within_host_evolution.R
echo "✓ Evolution analysis complete"

echo "[3/6] Basic variant annotation [~1 min]..."
Rscript 18_annotate_variants.R
echo "✓ Variant annotation complete"

echo "[4/6] Deep variant annotation with GFF [~1 min]..."
Rscript 20_variant_annotation_deep.R
echo "✓ Deep annotation complete"

echo "[5/6] Host context analysis [~1 min]..."
Rscript 19_host_context.R
echo "✓ Host context analysis complete"

echo "[6/6] Publication figures [~1 min]..."
Rscript 21_publication_figures.R
echo "✓ Publication figures generated"

echo "✓ Phase 3 complete: longitudinal candidate events and host context generated"

# ============================================================================
# Phase 4: Virulence Factor (VF) Deep Analysis
# ============================================================================
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PHASE 4: VF Deep Analysis [Est: 15 min]"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

echo "[1/13] Cross-sectional analysis..."
Rscript 23_vf_cross_sectional.R
echo "✓ VF cross-sectional done"

echo "[2/13] Longitudinal dynamics..."
Rscript 24_vf_longitudinal_dynamics.R
echo "✓ VF longitudinal done"

echo "[3/13] Lineage confounding check..."
Rscript 25_vf_lineage_vf_interaction.R
echo "✓ Lineage interaction checked"

echo "[4/13] VF gene modules..."
Rscript 26_vf_define_gene_modules.R
echo "✓ VF modules defined"

echo "[5/13] VF score framework..."
Rscript 27_vf_score_framework.R
echo "✓ VF scores analysed"

echo "[6/13] Transition case studies..."
Rscript 28_vf_transition_case_studies.R
echo "✓ Transition case studies done"

echo "[7/13] VF + AMR combined profile..."
Rscript 29_vf_amr_combined_profile.R
echo "✓ VF + AMR profile done"

echo "[8/13] UTI/Not_UTI diagnostic statistics..."
Rscript 32_uti_not_uti_diagnostic_stats.R
echo "✓ UTI/Not_UTI diagnostics written"

echo "[9/13] Mechanism-first add-on..."
Rscript 33_mechanism_first_addon.R
echo "✓ Mechanism-first add-on written"

echo "[10/13] Robustness-first add-on..."
Rscript 34_robustness_first_addon.R
echo "✓ Robustness-first add-on written"

echo "[11/13] Targeted statistical sensitivity add-on..."
Rscript 36_statistical_sensitivity_addon.R
echo "✓ Targeted statistical sensitivity add-on written"

echo "[12/13] Project summary tables..."
Rscript 30_vf_project_summary_tables.R
echo "✓ VF project summary tables written"

echo "[13/13] Final figure pack..."
Rscript 35_final_figure_pack.R
echo "✓ Final figure pack written"

echo "Archiving stale ASB-vs-UTI generated outputs..."
Rscript scripts/archive_legacy_asb_uti_outputs.R
echo "✓ Legacy ASB-vs-UTI generated outputs archived"

echo "Verifying UTI-vs-Not_UTI output alignment..."
Rscript scripts/verify_uti_not_uti_alignment.R
echo "✓ UTI-vs-Not_UTI alignment verified"

echo "✓ Phase 4 complete: VF Deep Analysis"

# ============================================================================
# Done
# ============================================================================
echo ""
echo "=========================================="
echo "✅ COMPLETE ANALYSIS FINISHED"
echo "Ended: $(date)"
echo "Total Runtime: ~1.5-2.5 hours"
echo "=========================================="
echo ""
echo "📊 Key Outputs:"
echo "   - results/clinical/status_map.csv"
echo "   - results/vf/vf_pa_all.csv"
echo "   - results/vf/vf_analysis_ready.csv"
echo "   - results/vf/vf_binary_uti_ready.csv"
echo "   - results/strain_compare/pairwise_metrics.csv"
echo "   - results/models/model_dataset_denominator.csv"
echo "   - results/longitudinal/variant_annotation_detailed.csv"
echo "   - plots/publication/Fig*.png"
echo "   - plots/vf/ (VF heatmaps)"
echo "   - plots/mlst/ (MLST plots)"
echo "   - plots/plasmids/ (Plasmid networks)"
echo ""
echo "📖 Next steps:"
echo "   1. Review results/summary/final_key_results_summary.md"
echo "   2. Review results/models/model_interpretation_warnings.txt"
echo "   3. Check plots/clinical, plots/vf, plots/publication for current UTI-vs-Not_UTI figures"
