#!/usr/bin/env node

// Kept as a compatibility entry point; the canonical v4 deliverable is the
// 25-slide onboarding review generated by the shared Longcycler-only engine.
await import("./build_onboarding_safe_deck.mjs");

