#!/usr/bin/env Rscript
suppressPackageStartupMessages({
  need <- c("fs","dplyr","readr","stringr","optparse","tools","glue")
  to_install <- setdiff(need, rownames(installed.packages()))
  if (length(to_install)) install.packages(to_install, repos = "https://cloud.r-project.org")
  library(fs); library(dplyr); library(readr); library(stringr)
  library(optparse); library(tools); library(glue)
})

opt <- OptionParser() |>
  add_option("--root", default=".", help="Project root (default: .)") |>
  add_option("--apply", action="store_true", default=FALSE, help="Apply moves/deletes") |>
  add_option("--days-old-tmp", type="integer", default=0,
             help="Only delete tmp* files older than N days (0 = any age).") |>
  parse_args()

root <- path_abs(opt$root)
setwd(root)

dir_create("results/legacy", recurse = TRUE)
dir_create("docs/papers", recurse = TRUE)
dir_create("docs/slides", recurse = TRUE)
dir_create("scripts", recurse = TRUE)

# 1) MANIFEST
info <- dir_info(path = root, recurse = TRUE, type = "any", follow = TRUE) |>
  transmute(
    path = path_abs(path),
    rel  = path_rel(path, start = root),
    type = as.character(type),
    size_bytes = as.double(size),
    mtime = as.POSIXct(modification_time),
    ext  = tolower(file_ext(path)),
    name = path_file(path),
    parent = path_dir(rel)
  )

# helper: age in days
info <- info |>
  mutate(age_days = as.numeric(difftime(Sys.time(), mtime, units = "days")))

# 2) CLASSIFICATION RULES
classify <- function(row) {
  nm <- row$name; rel <- row$rel; ext <- row$ext; typ <- row$type; parent <- row$parent
  # a) Always KEEP directories
  if (typ == "directory") return(c("keep",""))
  # b) KEEP source and project control
  if (str_detect(nm, "\\.R$|\\.Rmd$|\\.Rproj$|^README")) return(c("keep",""))
  if (rel %in% c("yellow","data","results","scripts",".git",".github")) return(c("keep",""))
  if (str_starts(rel, "yellow/")) return(c("keep",""))
  # c) MOVE docs to papers/slides
  if (ext %in% c("pdf","doc","docx")) return(c("move","docs/papers"))
  if (ext %in% c("ppt","pptx","key")) return(c("move","docs/slides"))
  # d) MOVE known legacy outputs at top-level (we’ll keep current outputs under results/)
  if (nm %in% c("vf_hits.rds","vfdb_hits_all_assemblies.csv",
                "vfdb_presence_absence_matrix.csv","vfdb_gain_loss_by_participant.csv")) {
    return(c("move","results/legacy"))
  }
  # e) DELETE obvious scratch at project root
  if (str_detect(nm, "^tmp") && path_dir(rel) == ".") {
    # respect age threshold
    if (is.na(row$age_days) || row$age_days >= opt$`days-old-tmp`) return(c("delete",""))
  }
  if (nm %in% c("triangle.ids","triangle.sorted") && path_dir(rel) == ".") {
    return(c("delete",""))
  }
  # f) KEEP anything already in results/ (pipeline outputs)
  if (str_starts(rel, "results/")) return(c("keep",""))
  # g) Everything else is UNKNOWN (manual review)
  return(c("unknown",""))
}

decisions <- purrr::pmap_dfr(info, function(...){
  row <- tibble(...)
  res <- classify(row[1,])
  tibble(
    rel = row$rel, type=row$type, size_bytes=row$size_bytes, mtime=row$mtime,
    ext=row$ext, parent=row$parent, age_days=row$age_days,
    action = res[1], target = res[2]
  )
})

manifest <- info |> select(rel, type, size_bytes, mtime, ext, parent, age_days) |>
  left_join(decisions, by = c("rel","type","size_bytes","mtime","ext","parent","age_days")) |>
  arrange(match(action, c("delete","move","unknown","keep")), desc(size_bytes))

write_csv(manifest, "audit_manifest.csv")

# 3) EMIT A CLEANUP PLAN SHELL SCRIPT (safe to read/edit)
lines <- c("#!/usr/bin/env bash",
           "# Generated by scripts/audit_rUTIs.R",
           "set -euo pipefail",
           "shopt -s nullglob",
           "")
moves <- manifest |> filter(action=="move", target!="") |>
  mutate(cmd = glue('mkdir -p "{target}" && mv -i "{rel}" "{target}/"')) |> pull(cmd)
deletes <- manifest |> filter(action=="delete") |>
  mutate(cmd = glue('rm -f "{rel}"')) |> pull(cmd)

plan <- c(lines,
          if (length(moves)) c("# Moves", moves, "") else "# No moves",
          if (length(deletes)) c("# Deletes", deletes, "") else "# No deletes",
          'echo "Done."')
writeLines(plan, "cleanup_plan.sh")
Sys.chmod("cleanup_plan.sh", mode = "0755")

message("\nWrote: audit_manifest.csv and cleanup_plan.sh")

if (!opt$apply) {
  message("\nDRY RUN ONLY (no changes made).")
  message("Next steps:")
  message("  1) Inspect audit_manifest.csv")
  message("  2) (Optional) Edit cleanup_plan.sh")
  message("  3) Run: bash cleanup_plan.sh  # to apply")
  quit(save="no", status=0)
}

# 4) APPLY (if --apply)
if (nrow(filter(manifest, action=="move", target!=""))>0) {
  unique(filter(manifest, action=="move", target!="")$target) |> unique() |> purrr::walk(dir_create)
  filter(manifest, action=="move", target!="") |>
    pwalk(function(rel, target, ...){
      file_move(rel, path(target, path_file(rel)))
    })
}
if (nrow(filter(manifest, action=="delete"))>0) {
  filter(manifest, action=="delete") |>
    pull(rel) |>
    purrr::walk(function(p) if (file_exists(p)) file_delete(p))
}

message("\nApplied moves/deletes. Re-running inventory to verify…")
# re-list to show final state
final <- dir_info(path = root, recurse = TRUE, type = "any", follow = TRUE)
write_csv(final |> transmute(rel = path_rel(path, root), type=type, size_bytes=as.double(size), mtime=modification_time), 
          "post_cleanup_manifest.csv")
message("Wrote post_cleanup_manifest.csv")
